### PR TITLE
Bugfix/dropdown hight

### PR DESCRIPTION
**Pull request by androsssos**
### Prerequisites

Please make sure you can check the following two boxes:

- [x] I have read the **CONTRIBUTING** document
- [x] My code follows the code style of this project

### Contribution Type

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [x] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- [ ] New feature (non-breaking change which adds functionality, make sure to open an associated issue first)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### Description

Dropdown Elements had a height of 50%. Which will lead to a cut view of elements. 
Reason is because drowdown has a top:-53px. 
This fix changed it to 40% to be on the save side and to make sure that the drowdown is not out of the screen on the top

### CODE REVIEW

**Review by klaidigorishti — APPROVED** [review]
LGTM - thanks!

**Review by FlorianRappl — APPROVED** [review]
LGTM even though something like `calc(45vh - 53px)` would potentially even be better.

**Comment by FlorianRappl** [comment]
(Reason: 10% of VH = unknown, so if the height is smaller than 530px then 40vh will still cut off things; 45vh - 53px takes 45vh as baseline and then subtracts something. So even in the case of a very high screen resolution you'd have some 5% padding + on smaller screens you additionally remove the 53px; making it always fit nicely).

**Comment by androsssos** [comment]
Hallo Florian,
I know that was what we discussed to use "calc(50vh - 53px)"
But after testing multiple dropdowns in the portal.
That was not enough. Specially when the element is on the very upper border (like language list in document center).
So I tried 40, and that was fine. But we definitely needs to run some more tests with different resolutions and pages.
However "45vh - 53px" seems also good.

Best regards
Andreas

Von: Florian Rappl ***@***.***>
Gesendet: Montag, 7. Februar 2022 09:33
An: ZEISS/precise-ui ***@***.***>
Cc: Post, Andreas ***@***.***>; Author ***@***.***>
Betreff: Re: [ZEISS/precise-ui] Bugfix/dropdown hight (PR #365)


@FlorianRappl approved this pull request.

LGTM even though something like calc(45vh - 53px) would potentially even be better.

-
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FZEISS%2Fprecise-ui%2Fpull%2F365%23pullrequestreview-874327396&data=04%7C01%7C%7Cde7623fefda24da8f2b808d9ea1484cf%7C28042244bb514cd680347776fa3703e8%7C1%7C0%7C637798196110722738%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=woWLOQm2ZLgcQtGhqB2QNWmLgqO1nWyuN2Z42t5Bah4%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMH6AMLLVX6HSV7HSGIHRJ3UZ57U3ANCNFSM5NWX5XQQ&data=04%7C01%7C%7Cde7623fefda24da8f2b808d9ea1484cf%7C28042244bb514cd680347776fa3703e8%7C1%7C0%7C637798196110722738%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BcZNC7X8q21IKot4480mRSOiycMefrkhC%2Fd3PW7ZZYY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cde7623fefda24da8f2b808d9ea1484cf%7C28042244bb514cd680347776fa3703e8%7C1%7C0%7C637798196110722738%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KFalWNRsXgW8t8UxKSAbm6dU%2B7h1vGTbPo63wSbAt9Q%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cde7623fefda24da8f2b808d9ea1484cf%7C28042244bb514cd680347776fa3703e8%7C1%7C0%7C637798196110722738%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CINq%2BbgXZefI3hBNsZMy76kbprG7yK3PeLDS9s9iJ5A%3D&reserved=0>.

**Comment by FlorianRappl** [comment]
> I know that was what we discussed to use "calc(50vh - 53px)"

Yeah that was one proposal @androsssos. However, as mentioned a better solution would be a combination - such as `40vh - 53px`. In the fixed case (e.g., 40vh) as argued it will fail (just make the height smaller than 530px and you'll see it immediately; if your testing already failed with 50vh - 53px then you'd see it even earlier in the same cases).

I am not sure what the sweet spot is - because I think a combination of `min-height` and `max-height` would also be good.

**Pull request merged**
