### PR TITLE
Resolve #108 issue (make carousel item clickable)

### LINKED ISSUE #108: Impossible to change a carousel item if it contains the link in itself.
### Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository?
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

### Versions

`0.6.1`

### Description

Impossible to drag a carousel item if it contains the link itself.

### Steps to Reproduce

1. Open https://precise-ui.io/#/Components/Carousel
2. Insert the code in the 1-st example:
```tsx
const { Carousel } = require('precise-ui');

<Carousel infinite>
  <a href="#1" style={{ height: '150px', width: '100%', backgroundColor: '#f3a', display: 'flex', justifyContent: 'center', alignItems: 'center'}}>
    First page
  </a>
  <a href="#2" style={{ height: '200px', width: '90%', backgroundColor: '#43c', display: 'flex', justifyContent: 'center', alignItems: 'center'}}>
    Second page
  </a>
  <a href="#3" style={{ height: '150px', width: '450px', backgroundColor: '#1f2', display: 'flex', justifyContent: 'center', alignItems: 'center'}}>
    Third page
  </a>
</Carousel>
```
3. Try to drag the tile.

**Expected behavior:** 
- Carousel item is changed. 

**Actual behavior:** 
- The page is changed.

**Environment details:** [any OS, any browser]

### Possible Solution

To be clarified...

### PR DESCRIPTION
**Pull request by dimabory**
### Prerequisites

Please make sure you can check the following two boxes:

- [x] I have read the **CONTRIBUTING** document
- [x] My code follows the code style of this project

### Contribution Type

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [x] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- [ ] New feature (non-breaking change which adds functionality, make sure to open an associated issue first)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

### Description

See #108

### CODE REVIEW

**Comment by kotielnikov** [comment]
changelog

**Comment by dimabory** [comment]
> changelog

Always forget about that. There is a fine library https://github.com/conventional-changelog/conventional-changelog, which does it automatically based on the commit message.

**Comment by kotielnikov** [comment]
Great! If you decide to for conventional commits you can get my fully support. Can be useful for portal as well

**Comment by dimabory** [comment]
> Great! If you decide to for conventional commits you can get my fully support. Can be useful for portal as well

Yeah, this is a cool tool, but it has strict rules, which should be followed by every contributor.

**Comment by kotielnikov** [comment]
I expect this can be enforced with some tooling

**Comment by dimabory** [comment]
> I expect this can be enforced with some tooling

Sure, for that reason there is https://github.com/conventional-changelog/commitlint

**Comment by dimabory** [comment]
@kotielnikov 	please approve

**Comment by kotielnikov** [comment]
@dimabory please fix review comments

**Pull request merged**
